---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Create nginx config
  template:
    src: nginx.j2
    dest: /etc/nginx/sites-available/default
    mode: 0644

- name: Enable nginx config
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: Restart nginx
  service:
    name: nginx
    state: restarted
